//! Tables used by the quick fixes: names LaTeX accepts, TikZ libraries,
//! Unicode characters pdfLaTeX does not know.

/// TikZ keys, shapes and styles that come from a library.
pub(crate) const TIKZ_KEY_LIBRARIES: &[(&str, &str)] = &[
    ("diamond", "shapes.geometric"),
    ("ellipse", "shapes.geometric"),
    ("trapezium", "shapes.geometric"),
    ("regular polygon", "shapes.geometric"),
    ("regular polygon sides", "shapes.geometric"),
    ("star", "shapes.geometric"),
    ("star points", "shapes.geometric"),
    ("isosceles triangle", "shapes.geometric"),
    ("kite", "shapes.geometric"),
    ("dart", "shapes.geometric"),
    ("cylinder", "shapes.geometric"),
    ("semicircle", "shapes.geometric"),
    ("circular sector", "shapes.geometric"),
    ("rectangle split", "shapes.multipart"),
    ("rectangle split parts", "shapes.multipart"),
    ("circle split", "shapes.multipart"),
    ("circle solidus", "shapes.multipart"),
    ("cloud", "shapes.symbols"),
    ("starburst", "shapes.symbols"),
    ("signal", "shapes.symbols"),
    ("tape", "shapes.symbols"),
    ("single arrow", "shapes.arrows"),
    ("double arrow", "shapes.arrows"),
    ("rounded rectangle", "shapes.misc"),
    ("chamfered rectangle", "shapes.misc"),
    ("cross out", "shapes.misc"),
    ("strike out", "shapes.misc"),
    ("decorate", "decorations.pathmorphing"),
    ("decoration", "decorations.pathmorphing"),
    ("pattern", "patterns"),
    ("pattern color", "patterns"),
    ("drop shadow", "shadows"),
    ("circular drop shadow", "shadows"),
    ("copy shadow", "shadows"),
    ("double copy shadow", "shadows"),
    ("fit", "fit"),
    ("on background layer", "backgrounds"),
    ("background rectangle", "backgrounds"),
    ("show background rectangle", "backgrounds"),
    ("framed", "backgrounds"),
    ("matrix of nodes", "matrix"),
    ("matrix of math nodes", "matrix"),
    ("name path", "intersections"),
    ("name path global", "intersections"),
    ("name intersections", "intersections"),
    ("state", "automata"),
    ("initial", "automata"),
    ("accepting", "automata"),
    ("start chain", "chains"),
    ("on chain", "chains"),
    ("grow cyclic", "trees"),
    ("spy using outlines", "spy"),
    ("spy using overlays", "spy"),
    ("mindmap", "mindmap"),
    ("concept", "mindmap"),
    ("angle radius", "angles"),
    ("angle eccentricity", "angles"),
    ("canvas is xy plane at z", "3d"),
    ("canvas is xz plane at y", "3d"),
    ("canvas is yz plane at x", "3d"),
    ("above=of", "positioning"),
];

/// Decorations and the library that defines them.
pub(crate) const TIKZ_DECORATIONS: &[(&str, &str)] = &[
    ("zigzag", "decorations.pathmorphing"),
    ("snake", "decorations.pathmorphing"),
    ("coil", "decorations.pathmorphing"),
    ("bumps", "decorations.pathmorphing"),
    ("saw", "decorations.pathmorphing"),
    ("random steps", "decorations.pathmorphing"),
    ("straight zigzag", "decorations.pathmorphing"),
    ("brace", "decorations.pathreplacing"),
    ("ticks", "decorations.pathreplacing"),
    ("border", "decorations.pathreplacing"),
    ("expanding waves", "decorations.pathreplacing"),
    ("waves", "decorations.pathreplacing"),
    ("markings", "decorations.markings"),
    ("text along path", "decorations.text"),
    ("text effects along path", "decorations.text"),
    ("footprints", "decorations.footprints"),
    ("fractal", "decorations.fractals"),
    ("shape backgrounds", "decorations.shapes"),
    ("crosses", "decorations.shapes"),
    ("triangles", "decorations.shapes"),
];

/// Arrow tips of the `arrows.meta` library.
pub(crate) const META_ARROWS: &[&str] = &[
    "Stealth",
    "Latex",
    "Triangle",
    "Kite",
    "Square",
    "Circle",
    "Ellipse",
    "Diamond",
    "Rectangle",
    "Turned Square",
    "Straight Barb",
    "Arc Barb",
    "Tee Barb",
    "Classical TikZ Rightarrow",
    "Computer Modern Rightarrow",
    "Implies",
    "Hooks",
    "Bar",
    "Bracket",
    "Parenthesis",
    "Rays",
    "Butt Cap",
    "Round Cap",
    "Triangle Cap",
    "Fast Triangle",
    "Fast Round",
    "To",
    "Tee Barb",
];

/// Arrow tips of the old `arrows` library.
pub(crate) const OLD_ARROWS: &[&str] = &[
    "stealth'",
    "latex'",
    "triangle 45",
    "triangle 60",
    "triangle 90",
    "open triangle 45",
    "open triangle 60",
    "open triangle 90",
    "angle 45",
    "angle 60",
    "angle 90",
    "diamond",
    "open diamond",
    "square",
    "open square",
    "circle",
    "open circle",
    "fast cap",
    "round cap",
    "butt cap",
    "triangle 90 cap",
    "hooks",
    "right hook",
    "left hook",
];

/// Common TikZ keys (for "did you mean").
pub(crate) const TIKZ_KEYS: &[&str] = &[
    "color",
    "draw",
    "fill",
    "thick",
    "thin",
    "very thick",
    "ultra thick",
    "very thin",
    "ultra thin",
    "semithick",
    "line width",
    "dashed",
    "dotted",
    "densely dashed",
    "loosely dashed",
    "densely dotted",
    "loosely dotted",
    "dash dot",
    "solid",
    "rounded corners",
    "sharp corners",
    "opacity",
    "fill opacity",
    "draw opacity",
    "text opacity",
    "text",
    "font",
    "anchor",
    "above",
    "below",
    "left",
    "right",
    "above left",
    "above right",
    "below left",
    "below right",
    "scale",
    "xscale",
    "yscale",
    "rotate",
    "xshift",
    "yshift",
    "shift",
    "minimum width",
    "minimum height",
    "minimum size",
    "inner sep",
    "outer sep",
    "node distance",
    "align",
    "text width",
    "shape",
    "circle",
    "rectangle",
    "coordinate",
    "pos",
    "midway",
    "near start",
    "near end",
    "at start",
    "at end",
    "sloped",
    "auto",
    "swap",
    "bend left",
    "bend right",
    "in",
    "out",
    "looseness",
    "loop",
    "domain",
    "samples",
    "smooth",
    "variable",
    "help lines",
    "step",
    "line cap",
    "line join",
    "double",
    "double distance",
    "postaction",
    "preaction",
    "transform shape",
    "label",
    "pin",
    "name",
    "radius",
    "x radius",
    "y radius",
    "start angle",
    "end angle",
    "delta angle",
    "ball color",
    "shading",
    "top color",
    "bottom color",
    "left color",
    "right color",
    "middle color",
    "inner color",
    "outer color",
    "even odd rule",
    "clip",
    "use as bounding box",
    "overlay",
    "remember picture",
    "baseline",
    "every node",
    "arrows",
    "shorten >",
    "shorten <",
    "->",
    "<-",
    "<->",
    "-|",
    "|-",
    "->>",
    "x",
    "y",
    "z",
    "grow",
    "level distance",
    "sibling distance",
    "text centered",
    "text ragged",
    "text badly centered",
    "execute at begin node",
];

/// Language options of babel.
pub(crate) const BABEL_LANGUAGES: &[&str] = &[
    "afrikaans",
    "albanian",
    "american",
    "australian",
    "austrian",
    "basque",
    "brazil",
    "brazilian",
    "breton",
    "british",
    "bulgarian",
    "canadian",
    "canadien",
    "catalan",
    "croatian",
    "czech",
    "danish",
    "dutch",
    "english",
    "esperanto",
    "estonian",
    "finnish",
    "french",
    "galician",
    "german",
    "greek",
    "hebrew",
    "hungarian",
    "icelandic",
    "indonesian",
    "interlingua",
    "irish",
    "italian",
    "latin",
    "lowersorbian",
    "magyar",
    "malay",
    "naustrian",
    "newzealand",
    "ngerman",
    "norsk",
    "nswissgerman",
    "nynorsk",
    "polish",
    "portuguese",
    "romanian",
    "russian",
    "samin",
    "scottish",
    "serbian",
    "slovak",
    "slovene",
    "spanish",
    "swedish",
    "swissgerman",
    "turkish",
    "UKenglish",
    "ukrainian",
    "uppersorbian",
    "USenglish",
    "welsh",
    "acadian",
];

/// Encodings of `inputenc`.
pub(crate) const INPUT_ENCODINGS: &[&str] = &[
    "utf8", "latin1", "latin2", "latin3", "latin4", "latin5", "latin9", "latin10", "ascii",
    "ansinew", "applemac", "cp1250", "cp1252", "cp437", "cp850", "cp858", "macce", "next",
];

/// Encodings of `fontenc`.
pub(crate) const FONT_ENCODINGS: &[&str] = &[
    "T1", "OT1", "T2A", "T2B", "T2C", "X2", "LGR", "TS1", "LY1", "T5", "TU", "OML", "OMS",
];

/// Keys of key-value options, by package.
pub(crate) const KEYVAL_KEYS: &[(&str, &[&str])] = &[
    (
        "graphicx",
        &[
            "width",
            "height",
            "totalheight",
            "keepaspectratio",
            "scale",
            "angle",
            "origin",
            "trim",
            "clip",
            "viewport",
            "draft",
            "page",
            "pagebox",
            "interpolate",
            "bb",
            "natwidth",
            "natheight",
            "hiresbb",
            "decodearray",
            "quiet",
            "type",
            "ext",
            "read",
            "command",
            "alt",
        ],
    ),
    (
        "geometry",
        &[
            "paper",
            "papername",
            "a4paper",
            "a5paper",
            "b5paper",
            "letterpaper",
            "legalpaper",
            "executivepaper",
            "landscape",
            "portrait",
            "margin",
            "hmargin",
            "vmargin",
            "left",
            "right",
            "top",
            "bottom",
            "inner",
            "outer",
            "lmargin",
            "rmargin",
            "tmargin",
            "bmargin",
            "textwidth",
            "textheight",
            "width",
            "height",
            "total",
            "body",
            "text",
            "includehead",
            "includefoot",
            "includeheadfoot",
            "includemp",
            "includeall",
            "ignorehead",
            "ignorefoot",
            "headheight",
            "headsep",
            "footskip",
            "marginparwidth",
            "marginparsep",
            "hcentering",
            "vcentering",
            "centering",
            "twoside",
            "bindingoffset",
            "heightrounded",
            "showframe",
            "nohead",
            "nofoot",
            "noheadfoot",
            "scale",
            "hscale",
            "vscale",
            "layout",
            "layoutsize",
            "driver",
            "pass",
            "reset",
            "columnsep",
            "footnotesep",
        ],
    ),
    (
        "hyperref",
        &[
            "colorlinks",
            "linkcolor",
            "citecolor",
            "urlcolor",
            "filecolor",
            "menucolor",
            "runcolor",
            "anchorcolor",
            "allcolors",
            "hidelinks",
            "pdftitle",
            "pdfauthor",
            "pdfsubject",
            "pdfkeywords",
            "pdfcreator",
            "pdfproducer",
            "pdfborder",
            "pdfstartview",
            "pdfpagemode",
            "pdfpagelayout",
            "pdfdisplaydoctitle",
            "pdfnewwindow",
            "pdflang",
            "bookmarks",
            "bookmarksopen",
            "bookmarksnumbered",
            "bookmarksopenlevel",
            "breaklinks",
            "draft",
            "final",
            "hyperindex",
            "hyperfootnotes",
            "linktoc",
            "linktocpage",
            "pageanchor",
            "plainpages",
            "unicode",
            "hypertexnames",
            "naturalnames",
            "backref",
            "pagebackref",
            "pdfusetitle",
            "linkbordercolor",
            "citebordercolor",
            "urlbordercolor",
        ],
    ),
    (
        "caption",
        &[
            "font",
            "labelfont",
            "textfont",
            "format",
            "labelformat",
            "labelsep",
            "justification",
            "singlelinecheck",
            "width",
            "margin",
            "skip",
            "position",
            "belowskip",
            "aboveskip",
            "indention",
            "hangindent",
            "parskip",
            "name",
            "type",
            "list",
            "listformat",
            "style",
            "size",
        ],
    ),
    (
        "listings",
        &[
            "language",
            "basicstyle",
            "keywordstyle",
            "commentstyle",
            "stringstyle",
            "numbers",
            "numberstyle",
            "stepnumber",
            "numbersep",
            "backgroundcolor",
            "showspaces",
            "showstringspaces",
            "showtabs",
            "frame",
            "rulecolor",
            "tabsize",
            "captionpos",
            "breaklines",
            "breakatwhitespace",
            "title",
            "caption",
            "label",
            "escapeinside",
            "morekeywords",
            "columns",
            "xleftmargin",
            "xrightmargin",
            "firstnumber",
            "literate",
            "extendedchars",
            "inputencoding",
            "upquote",
            "aboveskip",
            "belowskip",
            "emph",
            "emphstyle",
            "deletekeywords",
            "framerule",
            "framesep",
            "linewidth",
            "float",
            "floatplacement",
            "identifierstyle",
            "keepspaces",
            "mathescape",
            "texcl",
        ],
    ),
    (
        "enumitem",
        &[
            "label",
            "labelsep",
            "labelwidth",
            "labelindent",
            "leftmargin",
            "rightmargin",
            "itemindent",
            "itemsep",
            "parsep",
            "topsep",
            "partopsep",
            "noitemsep",
            "nosep",
            "start",
            "ref",
            "align",
            "font",
            "before",
            "after",
            "wide",
            "resume",
            "series",
            "style",
            "widest",
        ],
    ),
];

/// Commands that set the keys of a package (to know which keys a key-value
/// error is about).
pub(crate) const KEYVAL_COMMANDS: &[(&str, &str)] = &[
    ("includegraphics", "graphicx"),
    ("geometry", "geometry"),
    ("newgeometry", "geometry"),
    ("hypersetup", "hyperref"),
    ("captionsetup", "caption"),
    ("lstset", "listings"),
    ("lstinputlisting", "listings"),
    ("begin{lstlisting}", "listings"),
    ("setlist", "enumitem"),
    ("begin{itemize}", "enumitem"),
    ("begin{enumerate}", "enumitem"),
    ("begin{description}", "enumitem"),
];

/// Colour names in French and their xcolor name.
pub(crate) const FRENCH_COLORS: &[(&str, &str)] = &[
    ("bleu", "blue"),
    ("rouge", "red"),
    ("vert", "green"),
    ("jaune", "yellow"),
    ("noir", "black"),
    ("blanc", "white"),
    ("gris", "gray"),
    ("grisclair", "lightgray"),
    ("grisfonce", "darkgray"),
    ("violet", "violet"),
    ("rose", "pink"),
    ("marron", "brown"),
    ("brun", "brown"),
    ("pourpre", "purple"),
    ("citron", "lime"),
    ("sarcelle", "teal"),
    ("cyan", "cyan"),
    ("magenta", "magenta"),
    ("orange", "orange"),
    ("olive", "olive"),
];

/// Unicode characters pdfLaTeX does not know, and their LaTeX command.
/// `true`: a math command (written between `$` outside formulas).
pub(crate) const UNICODE_COMMANDS: &[(char, &str, bool)] = &[
    ('α', "\\alpha", true),
    ('β', "\\beta", true),
    ('γ', "\\gamma", true),
    ('δ', "\\delta", true),
    ('ε', "\\varepsilon", true),
    ('ϵ', "\\epsilon", true),
    ('ζ', "\\zeta", true),
    ('η', "\\eta", true),
    ('θ', "\\theta", true),
    ('ι', "\\iota", true),
    ('κ', "\\kappa", true),
    ('λ', "\\lambda", true),
    ('μ', "\\mu", true),
    ('ν', "\\nu", true),
    ('ξ', "\\xi", true),
    ('π', "\\pi", true),
    ('ρ', "\\rho", true),
    ('σ', "\\sigma", true),
    ('τ', "\\tau", true),
    ('υ', "\\upsilon", true),
    ('φ', "\\varphi", true),
    ('ϕ', "\\phi", true),
    ('χ', "\\chi", true),
    ('ψ', "\\psi", true),
    ('ω', "\\omega", true),
    ('Γ', "\\Gamma", true),
    ('Δ', "\\Delta", true),
    ('Θ', "\\Theta", true),
    ('Λ', "\\Lambda", true),
    ('Ξ', "\\Xi", true),
    ('Π', "\\Pi", true),
    ('Σ', "\\Sigma", true),
    ('Υ', "\\Upsilon", true),
    ('Φ', "\\Phi", true),
    ('Ψ', "\\Psi", true),
    ('Ω', "\\Omega", true),
    ('≤', "\\leq", true),
    ('≥', "\\geq", true),
    ('≠', "\\neq", true),
    ('≈', "\\approx", true),
    ('≃', "\\simeq", true),
    ('≡', "\\equiv", true),
    ('∼', "\\sim", true),
    ('∝', "\\propto", true),
    ('∞', "\\infty", true),
    ('∈', "\\in", true),
    ('∉', "\\notin", true),
    ('∋', "\\ni", true),
    ('⊂', "\\subset", true),
    ('⊃', "\\supset", true),
    ('⊆', "\\subseteq", true),
    ('⊇', "\\supseteq", true),
    ('∪', "\\cup", true),
    ('∩', "\\cap", true),
    ('∅', "\\emptyset", true),
    ('∀', "\\forall", true),
    ('∃', "\\exists", true),
    ('¬', "\\neg", true),
    ('∧', "\\wedge", true),
    ('∨', "\\vee", true),
    ('∑', "\\sum", true),
    ('∏', "\\prod", true),
    ('∫', "\\int", true),
    ('∮', "\\oint", true),
    ('√', "\\surd", true),
    ('∂', "\\partial", true),
    ('∇', "\\nabla", true),
    ('⇒', "\\Rightarrow", true),
    ('⇐', "\\Leftarrow", true),
    ('⇔', "\\Leftrightarrow", true),
    ('⟹', "\\Longrightarrow", true),
    ('⟸', "\\Longleftarrow", true),
    ('⟺', "\\Longleftrightarrow", true),
    ('↦', "\\mapsto", true),
    ('↔', "\\leftrightarrow", true),
    ('∘', "\\circ", true),
    ('⋅', "\\cdot", true),
    ('∙', "\\bullet", true),
    ('⊥', "\\perp", true),
    ('∥', "\\parallel", true),
    ('⊕', "\\oplus", true),
    ('⊗', "\\otimes", true),
    ('ℏ', "\\hbar", true),
    ('ℓ', "\\ell", true),
    ('ℵ', "\\aleph", true),
    ('♥', "\\heartsuit", true),
    ('♠', "\\spadesuit", true),
    ('♣', "\\clubsuit", true),
    ('♦', "\\diamondsuit", true),
    ('★', "\\star", true),
    ('⋆', "\\star", true),
    ('∗', "\\ast", true),
    ('′', "\\prime", true),
    ('⌊', "\\lfloor", true),
    ('⌋', "\\rfloor", true),
    ('⌈', "\\lceil", true),
    ('⌉', "\\rceil", true),
    ('⟨', "\\langle", true),
    ('⟩', "\\rangle", true),
    ('²', "^{2}", true),
    ('³', "^{3}", true),
    ('¹', "^{1}", true),
    ('₀', "_{0}", true),
    ('₁', "_{1}", true),
    ('₂', "_{2}", true),
    ('₃', "_{3}", true),
    ('\u{2009}', "\\,", false),
    ('\u{202F}', "\\,", false),
    ('\u{200B}', "", false),
    ('\u{FEFF}', "", false),
];

/// Colours of xcolor without options.
pub(crate) const BASE_COLORS: &[&str] = &[
    "black",
    "blue",
    "brown",
    "cyan",
    "darkgray",
    "gray",
    "green",
    "lightgray",
    "lime",
    "magenta",
    "olive",
    "orange",
    "pink",
    "purple",
    "red",
    "teal",
    "violet",
    "white",
    "yellow",
];

/// Colours of the `dvipsnames` option.
pub(crate) const DVIPS_COLORS: &[&str] = &[
    "Apricot",
    "Aquamarine",
    "Bittersweet",
    "Black",
    "Blue",
    "BlueGreen",
    "BlueViolet",
    "BrickRed",
    "Brown",
    "BurntOrange",
    "CadetBlue",
    "CarnationPink",
    "Cerulean",
    "CornflowerBlue",
    "Cyan",
    "Dandelion",
    "DarkOrchid",
    "Emerald",
    "ForestGreen",
    "Fuchsia",
    "Goldenrod",
    "Gray",
    "Green",
    "GreenYellow",
    "JungleGreen",
    "Lavender",
    "LimeGreen",
    "Magenta",
    "Mahogany",
    "Maroon",
    "Melon",
    "MidnightBlue",
    "Mulberry",
    "NavyBlue",
    "OliveGreen",
    "Orange",
    "OrangeRed",
    "Orchid",
    "Peach",
    "Periwinkle",
    "PineGreen",
    "Plum",
    "ProcessBlue",
    "Purple",
    "RawSienna",
    "Red",
    "RedOrange",
    "RedViolet",
    "Rhodamine",
    "RoyalBlue",
    "RoyalPurple",
    "RubineRed",
    "Salmon",
    "SeaGreen",
    "Sepia",
    "SkyBlue",
    "SpringGreen",
    "Tan",
    "TealBlue",
    "Thistle",
    "Turquoise",
    "Violet",
    "VioletRed",
    "White",
    "WildStrawberry",
    "Yellow",
    "YellowGreen",
    "YellowOrange",
];

/// Colours of the `svgnames` option.
pub(crate) const SVG_COLORS: &[&str] = &[
    "AliceBlue",
    "AntiqueWhite",
    "Aqua",
    "Aquamarine",
    "Azure",
    "Beige",
    "Bisque",
    "Black",
    "BlanchedAlmond",
    "Blue",
    "BlueViolet",
    "Brown",
    "BurlyWood",
    "CadetBlue",
    "Chartreuse",
    "Chocolate",
    "Coral",
    "CornflowerBlue",
    "Cornsilk",
    "Crimson",
    "Cyan",
    "DarkBlue",
    "DarkCyan",
    "DarkGoldenrod",
    "DarkGray",
    "DarkGreen",
    "DarkKhaki",
    "DarkMagenta",
    "DarkOliveGreen",
    "DarkOrange",
    "DarkOrchid",
    "DarkRed",
    "DarkSalmon",
    "DarkSeaGreen",
    "DarkSlateBlue",
    "DarkSlateGray",
    "DarkTurquoise",
    "DarkViolet",
    "DeepPink",
    "DeepSkyBlue",
    "DimGray",
    "DodgerBlue",
    "FireBrick",
    "FloralWhite",
    "ForestGreen",
    "Fuchsia",
    "Gainsboro",
    "GhostWhite",
    "Gold",
    "Goldenrod",
    "Gray",
    "Green",
    "GreenYellow",
    "Honeydew",
    "HotPink",
    "IndianRed",
    "Indigo",
    "Ivory",
    "Khaki",
    "Lavender",
    "LavenderBlush",
    "LawnGreen",
    "LemonChiffon",
    "LightBlue",
    "LightCoral",
    "LightCyan",
    "LightGoldenrod",
    "LightGoldenrodYellow",
    "LightGray",
    "LightGreen",
    "LightPink",
    "LightSalmon",
    "LightSeaGreen",
    "LightSkyBlue",
    "LightSlateBlue",
    "LightSlateGray",
    "LightSteelBlue",
    "LightYellow",
    "Lime",
    "LimeGreen",
    "Linen",
    "Magenta",
    "Maroon",
    "MediumAquamarine",
    "MediumBlue",
    "MediumOrchid",
    "MediumPurple",
    "MediumSeaGreen",
    "MediumSlateBlue",
    "MediumSpringGreen",
    "MediumTurquoise",
    "MediumVioletRed",
    "MidnightBlue",
    "MintCream",
    "MistyRose",
    "Moccasin",
    "NavajoWhite",
    "Navy",
    "NavyBlue",
    "OldLace",
    "Olive",
    "OliveDrab",
    "Orange",
    "OrangeRed",
    "Orchid",
    "PaleGoldenrod",
    "PaleGreen",
    "PaleTurquoise",
    "PaleVioletRed",
    "PapayaWhip",
    "PeachPuff",
    "Peru",
    "Pink",
    "Plum",
    "PowderBlue",
    "Purple",
    "Red",
    "RosyBrown",
    "RoyalBlue",
    "SaddleBrown",
    "Salmon",
    "SandyBrown",
    "SeaGreen",
    "Seashell",
    "Sienna",
    "Silver",
    "SkyBlue",
    "SlateBlue",
    "SlateGray",
    "Snow",
    "SpringGreen",
    "SteelBlue",
    "Tan",
    "Teal",
    "Thistle",
    "Tomato",
    "Turquoise",
    "Violet",
    "VioletRed",
    "Wheat",
    "White",
    "WhiteSmoke",
    "Yellow",
];
