//! Embeds the knowledge base (`data/`) into the binary.
//!
//! Every file under `data/packages`, `data/templates` and `data/help` is listed
//! in a generated `embedded.rs` so that adding a package description, a
//! template or a help page never requires touching Rust code.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let data = manifest.join("data");
    println!("cargo:rerun-if-changed=data");

    let mut out = String::from("// @generated by build.rs — do not edit.\n\n");

    // Package knowledge base: data/packages/*.json
    let packages = sorted_files(&data.join("packages"));
    out.push_str("/// `(file stem, JSON)` for every package description.\n");
    out.push_str("pub static PACKAGES: &[(&str, &str)] = &[\n");
    for path in &packages {
        if path.extension().is_some_and(|e| e == "json") {
            let stem = path.file_stem().unwrap().to_string_lossy();
            writeln!(out, "    ({stem:?}, include_str!({:?})),", path.display()).unwrap();
        }
    }
    out.push_str("];\n\n");

    // Templates: data/templates/<id>/**
    out.push_str("/// `(template id, relative path, bytes)` for every template file.\n");
    out.push_str("pub static TEMPLATE_FILES: &[(&str, &str, &[u8])] = &[\n");
    for dir in sorted_dirs(&data.join("templates")) {
        let id = dir.file_name().unwrap().to_string_lossy().to_string();
        let mut files = Vec::new();
        collect_files(&dir, &mut files);
        files.sort();
        for file in files {
            let rel = file
                .strip_prefix(&dir)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            writeln!(
                out,
                "    ({id:?}, {rel:?}, include_bytes!({:?})),",
                file.display()
            )
            .unwrap();
        }
    }
    out.push_str("];\n\n");

    // Help pages: data/help/<lang>/<id>.md
    out.push_str("/// `(language, page id, markdown)` for every help page.\n");
    out.push_str("pub static HELP_PAGES: &[(&str, &str, &str)] = &[\n");
    for dir in sorted_dirs(&data.join("help")) {
        let lang = dir.file_name().unwrap().to_string_lossy().to_string();
        for file in sorted_files(&dir) {
            if file.extension().is_some_and(|e| e == "md") {
                let id = file.file_stem().unwrap().to_string_lossy();
                writeln!(
                    out,
                    "    ({lang:?}, {id:?}, include_str!({:?})),",
                    file.display()
                )
                .unwrap();
            }
        }
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded.rs");
    fs::write(dest, out).unwrap();
}

fn sorted_files(dir: &Path) -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = fs::read_dir(dir)
        .map(|rd| {
            rd.filter_map(|e| e.ok())
                .map(|e| e.path())
                .filter(|p| p.is_file())
                .collect()
        })
        .unwrap_or_default();
    v.sort();
    v
}

fn sorted_dirs(dir: &Path) -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = fs::read_dir(dir)
        .map(|rd| {
            rd.filter_map(|e| e.ok())
                .map(|e| e.path())
                .filter(|p| p.is_dir())
                .collect()
        })
        .unwrap_or_default();
    v.sort();
    v
}

fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for entry in rd.filter_map(|e| e.ok()) {
        let path = entry.path();
        let name = entry.file_name();
        if name.to_string_lossy().starts_with('.') {
            continue;
        }
        if path.is_dir() {
            collect_files(&path, out);
        } else {
            out.push(path);
        }
    }
}
